#!/bin/bash

# abs_path: credit to http://stackoverflow.com/a/13087801
abs_path () {
  pushd "$1" >/dev/null
  pwd
  popd >/dev/null
}

# symlink everything in ./Packages/ to Sublime Text's Packages/
SUBLIME_DIR=$HOME/Library/Application\ Support/Sublime\ Text\ 2/Packages
PACKAGE_DIR="$(abs_path $(dirname $0)/Packages)"
for DIR in $PACKAGE_DIR/*; do
  NAME="$SUBLIME_DIR/$(basename "$DIR")"
  if [[ -e "$NAME" ]]; then
    if [[ -L "$NAME" ]]; then
      rm "$NAME"
    else
      mv "$NAME" "$NAME.backup"
    fi
  fi
  ln -sfv "$DIR" "$NAME"
done
