#!/bin/sh
#
# bootstrap installs things.

# If on OS X, run Homebrew
if [ $(uname -s) = "Darwin" ] 
then
	. script/homebrew
fi

# Run the install (I'd like to pull this out of rake, eventually)
rake install
